/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package botjava;

import botjava.Commands.Buttons;
import botjava.Commands.Embed;
import botjava.Commands.Sum;
import botjava.Commands.music.NowPlaying;
import botjava.Commands.music.Play;
import botjava.Commands.music.Queue;
import botjava.Commands.music.Repeat;
import botjava.Commands.music.Skip;
import botjava.Commands.music.Stop;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

public class App {
    public static void main(String[] args) { 
       JDA jda = JDABuilder.createDefault(Token.TOKEN).build();
       jda.addEventListener(new Listeners());
       CommandManager manager = new CommandManager();
       manager.add(new Sum());
       manager.add(new Embed());
       manager.add(new Buttons());
       manager.add(new Play());
       manager.add(new Skip());
       manager.add(new Stop());
       manager.add(new NowPlaying());
       manager.add(new Queue());
       manager.add(new Repeat());
       jda.addEventListener(manager);
    }

    /*Guild - usado em um server específico
     * Global - usado em qualquer lugar (jda)
     */

    public Object getGreeting() {
        return null;
    }
}
