/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package botjava;

import org.jetbrains.annotations.TestOnly;

class AppTest {
    @TestOnly void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(Object greeting, String string) {
    }
}
